### PR TITLE
Revert "Add new glyphs from VS 2019."

### PR DESCRIPTION
**Pull request by madskristensen**
Reverts madskristensen/GlyphList#1

### CODE REVIEW

**Comment by madskristensen** [comment]
This caused issues with the alignments of the icons and names

**Comment by KirillOsenkov** [comment]
Curious what went wrong there. I do see the icons not matching anymore (e.g. `CSFileNode` is 
image
but is supposed to be http://glyphlist.azurewebsites.net/img/images/CSFileNode.png

Weird that if I request http://glyphlist.azurewebsites.net/img/images/CSFileNode.png separately the icon is correct, and I did clear my browser cache...

Any idea why the alignment was botched? Was it a caching issue?

**Comment by madskristensen** [comment]
not sure, I think I need to do a full export again from scratch to fix it up. These days I use KnownMonikers Explorer extension for VS instead of this website. Have you tried it?

**Comment by KirillOsenkov** [comment]
Yes, it's nice, but I still use the website out of habit.

I'm pretty sure when you saw problems it was the cache partially updated - if you clear the browser cache using F12 tools (Ctrl+F5 doesn't fully clear in my experience) maybe it would have been fine?

**Pull request merged**
